GET http://localhost:2000/users

###
GET http://localhost:2000/users/list

###
GET http://localhost:2000/userName/Simonpine2

###
GET http://localhost:2000/user/Simonpine2


###
# GET http://localhost:3000/task/19

###
# GET http://localhost:3000/tasks/count
###
POST http://localhost:2000/users
Content-Type: application/json

{
    "userName": "Andres",
    "clubs": [],
    "pasword": "asdasd",
    "question": "Favorite video game",
    "answer": "FreeFire"
}
###
DELETE http://localhost:2000/users/simonp


###
PUT http://localhost:2000/user/SimonPine
Content-Type: application/json


  {
    "userName": "SimonPine2",
    "clubs": "[]",
    "pasword": "88a6e9827dc732524299c9dca51bbd39",
    "userImg": null,
    "question": "Name fo your firts mas",
    "answer": "316e43b7f5c616eb112d8ed6c80ff403"
  }


###
DELETE http://localhost:2000/clubs/5qf1xzu8ch7